"""chore: initial migration

Revision ID: 5c77959b8455
Revises:
Create Date: 2022-07-20 14:17:01.078688

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "5c77959b8455"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tasks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tasks")
    # ### end Alembic commands ###
